
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.gcalendarinterpreter.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FechaFin = 9;
  public static final int dos_puntos = 12;
  public static final int Evento = 6;
  public static final int FECHA_LITERAL = 3;
  public static final int STRING_LITERAL = 2;
  public static final int Descripcion = 11;
  public static final int EOF = 0;
  public static final int Titulo = 7;
  public static final int FechaInicio = 8;
  public static final int Ubicacion = 10;
  public static final int New = 5;
  public static final int error = 1;
  public static final int HORA_LITERAL = 4;
  public static final int SEPARATOR = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "STRING_LITERAL",
  "FECHA_LITERAL",
  "HORA_LITERAL",
  "new",
  "Evento",
  "Titulo",
  "FechaInicio",
  "FechaFin",
  "Ubicacion",
  "Descripcion",
  "dos_puntos",
          "SEPARATOR"
  };
}

